### ISSUE TITLE
Tmux Refac

### ISSUE THREAD

**Issue by leouchoa** [leouchoa/dotfiles#13]
# TODO

- [x] Make it work in linux as well, apparently is not good ([done](https://github.com/leouchoa/.dotfiles/commit/37069df6ceeea5797d4fa1d02f46f64d17d143e6)).
- [x] Change the UI, add just basic stuff and signs ([done](https://github.com/leouchoa/.dotfiles/commit/37069df6ceeea5797d4fa1d02f46f64d17d143e6)).
- [ ] Get proper bindings for ressurrect / continuum
