### ISSUE TITLE
gh issue checkout with `fzf` and `awk`

### ISSUE THREAD

**Issue by leouchoapedreira** [leouchoa/dotfiles#8]
# Goal

Using `gh`, `fzf`, and `awk`:

1. get a list of issues and pretty print with `fzf`
2. use `awk` to format the checkout into this style: `<type>/<issue_number>-issue-description-short`

Here's the current progress:

```
GH_FORCE_TTY=100% gh issue list | fzf --ansi --preview 'GH_FORCE_TTY=100% gh issue view {1}' --preview-window down --header-lines 3 | awk '{print $3}'
```

**TODO:**

- [X] list issues and preview with `fzf`
- [ ] get `awk` to correclty format the output
- [ ] checkout to branch `awk` output
